service: wopi

provider:
  name: aws
  runtime: nodejs4.3

plugins:
  - serverless-webpack

custom:
  webpack:
    packager: 'yarn'      # Defaults to npm
    packagerOptions: {}   # Optional, depending on the selected packager

functions:
  CheckFileInfo:
    handler: handler.wopi
    events:
     - http:
         path: wopi/files/{id}
         method: get
  GetFile:
    handler: handler.wopi
    events:
     - http:
         path: wopi/files/{id}/contents
         method: get
  SetFileMetadata:
    handler: handler.wopi
    events:
     - http:
         path: wopi/files/{id}
         method: post
  PutFile:
    handler: handler.wopi
    events:
     - http:
         path: wopi/files/{id}/contents
         method: post

    